### ISSUE TITLE
Attach a task by its id instead of its name

### ISSUE THREAD

**Issue by vtexier** [germaniumhq/adhesive#1]
I want to use adhesive as a BPMN engine.

Is it possible to use the task decorator to attach the function to the task ID instead of the name.

I need to let my customers change the task names, while I use IDs to attach code to tasks. 

If not, can you guide me in the code where the re expression is used to match against the name ?
Or is it something too hard to change ?

**Comment by bmustiata** [comment]
The actual matching is here:

https://github.com/germaniumhq/adhesive/blob/24697dedd4918ad3df328ef994d0597e419b5945/adhesive/model/process_validator.py#L151-L156

The _task definition_ is the python implementation of a task which currently gets matched using regex. The `ProcessTask` is the actual node in the BPMN graph.

You could change the task definition to accept an `Optional[Union[str, Iterable[str]]]` task_id as well, and if they exist they should have precedence over the regex matching.

**Comment by vtexier** [comment]
Thanks for your help!

I realized that this feature was not what I needed, but I have used your hint to add support for `serviceTask` created by the [BPMN Zeebe Modeler](https://github.com/zeebe-io/zeebe-modeler).
